<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import api, { errorMessage, validationErrors } from '../../composables/useAdminApi'
import AdminPageHeader from '../../components/AdminPageHeader.vue'

const props = defineProps({ id: { type: String, default: '' } })
const router = useRouter(); const saving=ref(false); const loading=ref(!!props.id); const errors=ref({}); const requestError=ref('')
const form=reactive({name:'',display_name:'',registration_number:'',tax_number:'',vat_number:'',registered_address:'',billing_address:'',billing_details:'',status:'active',internal_notes:''})
const editing=computed(()=>Boolean(props.id))
onMounted(async()=>{if(!props.id)return;try{Object.assign(form,(await api.get(`/clients/${props.id}`)).data.data)}catch(e){requestError.value=errorMessage(e)}finally{loading.value=false}})
async function submit(){saving.value=true;errors.value={};requestError.value='';try{const response=editing.value?await api.put(`/clients/${props.id}`,form):await api.post('/clients',form);router.push({name:'clients.show',params:{id:response.data.data.id}})}catch(e){errors.value=validationErrors(e);requestError.value=errorMessage(e)}finally{saving.value=false}}
</script>

<template><div class="space-y-6"><AdminPageHeader :title="editing?'Edit client':'New client'" eyebrow="Clients"><RouterLink class="admin-button admin-button--quiet" :to="editing?{name:'clients.show',params:{id}}:{name:'clients.index'}">Cancel</RouterLink></AdminPageHeader><p v-if="requestError" class="border border-red-700 bg-red-50 p-4 text-sm text-red-800">{{ requestError }}</p><p v-if="loading" class="py-20 text-center">Loading…</p><form v-else class="grid max-w-5xl gap-6 lg:grid-cols-2" @submit.prevent="submit"><section class="space-y-4 border border-dark bg-light p-5 sm:p-6"><h2 class="font-mono text-base font-bold uppercase">Legal information</h2><div class="admin-field"><label for="name">Legal / business name</label><input id="name" v-model="form.name" required><p v-if="errors.name" class="admin-error">{{errors.name[0]}}</p></div><div class="admin-field"><label for="display_name">Display / trading name</label><input id="display_name" v-model="form.display_name"></div><div class="grid gap-4 sm:grid-cols-3"><div class="admin-field"><label for="ico">IČO</label><input id="ico" v-model="form.registration_number"></div><div class="admin-field"><label for="dic">DIČ</label><input id="dic" v-model="form.tax_number"></div><div class="admin-field"><label for="vat">IČ DPH</label><input id="vat" v-model="form.vat_number"></div></div><div class="admin-field"><label for="status">Status</label><select id="status" v-model="form.status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></div></section><section class="space-y-4 border border-dark bg-light p-5 sm:p-6"><h2 class="font-mono text-base font-bold uppercase">Addresses & notes</h2><div class="admin-field"><label for="registered">Registered address</label><textarea id="registered" v-model="form.registered_address" rows="3"></textarea></div><div class="admin-field"><label for="billing_address">Billing address</label><textarea id="billing_address" v-model="form.billing_address" rows="3"></textarea></div><div class="admin-field"><label for="billing_details">Billing details</label><textarea id="billing_details" v-model="form.billing_details" rows="3"></textarea></div><div class="admin-field"><label for="notes">Internal notes</label><textarea id="notes" v-model="form.internal_notes" rows="4"></textarea></div></section><div class="flex justify-end lg:col-span-2"><button class="admin-button bg-dark text-light" :disabled="saving">{{saving?'Saving…':'Save client'}}</button></div></form></div></template>