<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import api, { errorMessage, validationErrors } from '../../composables/useAdminApi'
import AdminPageHeader from '../../components/AdminPageHeader.vue'

const props = defineProps({ id: { type: String, default: '' } })
const router = useRouter(); const lookups=ref({companies:[],service_products:[]}); const contacts=ref([]); const loading=ref(true); const saving=ref(false); const errors=ref({}); const requestError=ref(''); const initialCompany=ref(null)
const form=reactive({company_id:'',service_product_id:'',name:'',url:'',project_code:'',summary:'',internal_notes:'',portal_status:'draft',started_at:'',completed_at:'',contact_ids:[]})
const editing=computed(()=>Boolean(props.id))
async function loadContacts(companyId, preserve=false){if(!companyId){contacts.value=[];form.contact_ids=[];return}contacts.value=(await api.get(`/companies/${companyId}/contacts/options`)).data;if(!preserve)form.contact_ids=form.contact_ids.filter(id=>contacts.value.some(contact=>contact.id===id))}
watch(()=>form.company_id,async(value,oldValue)=>{if(oldValue!==undefined&&value!==oldValue)await loadContacts(value,value===initialCompany.value)})
onMounted(async()=>{try{lookups.value=(await api.get('/lookups')).data;if(props.id){const project=(await api.get(`/projects/${props.id}`)).data.data;initialCompany.value=project.company_id;Object.assign(form,{...project,portal_status:project.status,contact_ids:project.contacts.map(contact=>contact.id)});await loadContacts(project.company_id,true)}}catch(e){requestError.value=errorMessage(e)}finally{loading.value=false}})
async function submit(){saving.value=true;errors.value={};requestError.value='';try{const response=editing.value?await api.put(`/projects/${props.id}`,form):await api.post('/projects',form);router.push({name:'projects.show',params:{id:response.data.data.id}})}catch(e){errors.value=validationErrors(e);requestError.value=errorMessage(e)}finally{saving.value=false}}
</script>

<template>
  <div class="space-y-6"><AdminPageHeader :title="editing?'Edit project':'New project'" eyebrow="Projects"><RouterLink class="admin-button admin-button--quiet" :to="editing?{name:'projects.show',params:{id}}:{name:'projects.index'}">Cancel</RouterLink></AdminPageHeader>
    <p v-if="requestError" class="border border-red-700 bg-red-50 p-4 text-sm text-red-800">{{requestError}}</p><p v-if="loading" class="py-20 text-center">Loading…</p>
    <form v-else class="grid max-w-6xl gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]" @submit.prevent="submit">
      <div class="space-y-6"><section class="grid gap-4 border border-dark bg-light p-5 sm:grid-cols-2 sm:p-6"><h2 class="font-mono font-bold uppercase sm:col-span-2">Project identity</h2><div class="admin-field"><label for="project-name">Name</label><input id="project-name" v-model="form.name" required><p v-if="errors.name" class="admin-error">{{errors.name[0]}}</p></div><div class="admin-field"><label for="project-code">Project code</label><input id="project-code" v-model="form.project_code"></div><div class="admin-field"><label for="project-company">Client</label><select id="project-company" v-model="form.company_id" required><option value="" disabled>Select client</option><option v-for="company in lookups.companies" :key="company.id" :value="company.id">{{company.display_name||company.name}}</option></select><p v-if="errors.company_id" class="admin-error">{{errors.company_id[0]}}</p></div><div class="admin-field"><label for="project-service">Service product</label><select id="project-service" v-model="form.service_product_id" required><option value="" disabled>Select product</option><option v-for="product in lookups.service_products" :key="product.id" :value="product.id" :disabled="!product.active&&product.id!==form.service_product_id">{{product.name}}{{product.active?'':' (inactive)'}}</option></select><p v-if="errors.service_product_id" class="admin-error">{{errors.service_product_id[0]}}</p></div><div class="admin-field sm:col-span-2"><label for="project-url">Internal URL slug</label><input id="project-url" v-model="form.url" placeholder="Generated from name when blank"><p v-if="errors.url" class="admin-error">{{errors.url[0]}}</p></div><div class="admin-field sm:col-span-2"><label for="project-summary">Summary</label><textarea id="project-summary" v-model="form.summary" rows="4"></textarea></div><div class="admin-field sm:col-span-2"><label for="project-notes">Internal notes</label><textarea id="project-notes" v-model="form.internal_notes" rows="5"></textarea></div></section></div>
      <aside class="space-y-6"><section class="space-y-4 border border-dark bg-light p-5"><h2 class="font-mono font-bold uppercase">Lifecycle</h2><div class="admin-field"><label for="project-state">Status</label><select id="project-state" v-model="form.portal_status"><option value="draft">Draft</option><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="archived">Archived</option></select></div><div class="admin-field"><label for="started">Started</label><input id="started" v-model="form.started_at" type="date"></div><div class="admin-field"><label for="completed">Completed</label><input id="completed" v-model="form.completed_at" type="date"><p v-if="errors.completed_at" class="admin-error">{{errors.completed_at[0]}}</p></div></section><section class="space-y-3 border border-dark bg-light p-5"><h2 class="font-mono font-bold uppercase">Assigned contacts</h2><p v-if="!form.company_id" class="text-sm text-neutral-600">Select a client first.</p><p v-else-if="!contacts.length" class="text-sm text-neutral-600">This client has no active contacts.</p><label v-for="contact in contacts" :key="contact.id" class="flex gap-3 border-b border-neutral-200 pb-3 text-sm last:border-0"><input v-model="form.contact_ids" type="checkbox" :value="contact.id"><span><strong>{{contact.first_name}} {{contact.last_name}}</strong><small class="block text-neutral-500">{{contact.email}}</small></span></label><p v-if="errors.contact_ids" class="admin-error">{{errors.contact_ids[0]}}</p></section><button class="admin-button w-full bg-dark text-light" :disabled="saving">{{saving?'Saving...':'Save project'}}</button></aside>
    </form>
  </div>
</template>